package com.biz.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysArea<M extends BaseSysArea<M>> extends Model<M> implements IBean {

	public void setPkArea(java.lang.Integer pkArea) {
		set("PK_AREA", pkArea);
	}

	public java.lang.Integer getPkArea() {
		return get("PK_AREA");
	}

	public void setID(java.lang.Integer ID) {
		set("ID", ID);
	}

	public java.lang.Integer getID() {
		return get("ID");
	}

	public void setNAME(java.lang.String NAME) {
		set("NAME", NAME);
	}

	public java.lang.String getNAME() {
		return get("NAME");
	}

	public void setPID(java.lang.Integer PID) {
		set("PID", PID);
	}

	public java.lang.Integer getPID() {
		return get("PID");
	}

	public void setMINI(java.lang.String MINI) {
		set("MINI", MINI);
	}

	public java.lang.String getMINI() {
		return get("MINI");
	}

	public void setLEVEL(java.lang.Integer LEVEL) {
		set("LEVEL", LEVEL);
	}

	public java.lang.Integer getLEVEL() {
		return get("LEVEL");
	}

	public void setRootId(java.lang.Integer rootId) {
		set("ROOT_ID", rootId);
	}

	public java.lang.Integer getRootId() {
		return get("ROOT_ID");
	}

}
