package com.biz.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysLog<M extends BaseSysLog<M>> extends Model<M> implements IBean {

	public void setPkLog(java.lang.Integer pkLog) {
		set("PK_LOG", pkLog);
	}

	public java.lang.Integer getPkLog() {
		return get("PK_LOG");
	}

	public void setFkUser(java.lang.Integer fkUser) {
		set("FK_USER", fkUser);
	}

	public java.lang.Integer getFkUser() {
		return get("FK_USER");
	}

	public void setOptType(java.lang.Integer optType) {
		set("OPT_TYPE", optType);
	}

	public java.lang.Integer getOptType() {
		return get("OPT_TYPE");
	}

	public void setTableName(java.lang.String tableName) {
		set("TABLE_NAME", tableName);
	}

	public java.lang.String getTableName() {
		return get("TABLE_NAME");
	}

	public void setBeforeDatas(java.lang.String beforeDatas) {
		set("BEFORE_DATAS", beforeDatas);
	}

	public java.lang.String getBeforeDatas() {
		return get("BEFORE_DATAS");
	}

	public void setAfterDatas(java.lang.String afterDatas) {
		set("AFTER_DATAS", afterDatas);
	}

	public java.lang.String getAfterDatas() {
		return get("AFTER_DATAS");
	}

	public void setInsertTime(java.util.Date insertTime) {
		set("INSERT_TIME", insertTime);
	}

	public java.util.Date getInsertTime() {
		return get("INSERT_TIME");
	}

	public void setCreateById(java.lang.Integer createById) {
		set("CREATE_BY_ID", createById);
	}

	public java.lang.Integer getCreateById() {
		return get("CREATE_BY_ID");
	}

	public void setCreateByTime(java.util.Date createByTime) {
		set("CREATE_BY_TIME", createByTime);
	}

	public java.util.Date getCreateByTime() {
		return get("CREATE_BY_TIME");
	}

	public void setUpdateById(java.lang.Integer updateById) {
		set("UPDATE_BY_ID", updateById);
	}

	public java.lang.Integer getUpdateById() {
		return get("UPDATE_BY_ID");
	}

	public void setUpdateByTime(java.util.Date updateByTime) {
		set("UPDATE_BY_TIME", updateByTime);
	}

	public java.util.Date getUpdateByTime() {
		return get("UPDATE_BY_TIME");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("IS_VALID", isValid);
	}

	public java.lang.Integer getIsValid() {
		return get("IS_VALID");
	}

}
