package com.biz.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysLanguageCfg<M extends BaseSysLanguageCfg<M>> extends Model<M> implements IBean {

	public void setPkLanguageCfg(java.lang.Integer pkLanguageCfg) {
		set("PK_LANGUAGE_CFG", pkLanguageCfg);
	}

	public java.lang.Integer getPkLanguageCfg() {
		return get("PK_LANGUAGE_CFG");
	}

	public void setCN(java.lang.String CN) {
		set("CN", CN);
	}

	public java.lang.String getCN() {
		return get("CN");
	}

	public void setEN(java.lang.String EN) {
		set("EN", EN);
	}

	public java.lang.String getEN() {
		return get("EN");
	}

	public void setCreateById(java.lang.Integer createById) {
		set("CREATE_BY_ID", createById);
	}

	public java.lang.Integer getCreateById() {
		return get("CREATE_BY_ID");
	}

	public void setCreateByTime(java.util.Date createByTime) {
		set("CREATE_BY_TIME", createByTime);
	}

	public java.util.Date getCreateByTime() {
		return get("CREATE_BY_TIME");
	}

	public void setUpdateById(java.lang.Integer updateById) {
		set("UPDATE_BY_ID", updateById);
	}

	public java.lang.Integer getUpdateById() {
		return get("UPDATE_BY_ID");
	}

	public void setUpdateByTime(java.util.Date updateByTime) {
		set("UPDATE_BY_TIME", updateByTime);
	}

	public java.util.Date getUpdateByTime() {
		return get("UPDATE_BY_TIME");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("IS_VALID", isValid);
	}

	public java.lang.Integer getIsValid() {
		return get("IS_VALID");
	}

}
