package com.biz.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysSms<M extends BaseSysSms<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setSmsType(java.lang.Integer smsType) {
		set("smsType", smsType);
	}

	public java.lang.Integer getSmsType() {
		return get("smsType");
	}

	public void setToPhones(java.lang.String toPhones) {
		set("toPhones", toPhones);
	}

	public java.lang.String getToPhones() {
		return get("toPhones");
	}

	public void setSendTime(java.util.Date sendTime) {
		set("sendTime", sendTime);
	}

	public java.util.Date getSendTime() {
		return get("sendTime");
	}

	public void setEncode(java.lang.String encode) {
		set("encode", encode);
	}

	public java.lang.String getEncode() {
		return get("encode");
	}

	public void setResStatus(java.lang.String resStatus) {
		set("resStatus", resStatus);
	}

	public java.lang.String getResStatus() {
		return get("resStatus");
	}

	public void setResMsg(java.lang.String resMsg) {
		set("resMsg", resMsg);
	}

	public java.lang.String getResMsg() {
		return get("resMsg");
	}

	public void setSid(java.lang.String sid) {
		set("sid", sid);
	}

	public java.lang.String getSid() {
		return get("sid");
	}

	public void setOverLengthIgnore(java.lang.String overLengthIgnore) {
		set("overLengthIgnore", overLengthIgnore);
	}

	public java.lang.String getOverLengthIgnore() {
		return get("overLengthIgnore");
	}

	public void setSendRealTime(java.lang.String sendRealTime) {
		set("sendRealTime", sendRealTime);
	}

	public java.lang.String getSendRealTime() {
		return get("sendRealTime");
	}

	public void setRetryTime(java.lang.Integer retryTime) {
		set("retryTime", retryTime);
	}

	public java.lang.Integer getRetryTime() {
		return get("retryTime");
	}

	public void setCurRetryTime(java.lang.Integer curRetryTime) {
		set("curRetryTime", curRetryTime);
	}

	public java.lang.Integer getCurRetryTime() {
		return get("curRetryTime");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setRecTime(java.util.Date recTime) {
		set("recTime", recTime);
	}

	public java.util.Date getRecTime() {
		return get("recTime");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setBisExpInfo(java.lang.String bisExpInfo) {
		set("bisExpInfo", bisExpInfo);
	}

	public java.lang.String getBisExpInfo() {
		return get("bisExpInfo");
	}

	public void setOriginalId(java.lang.Long originalId) {
		set("originalId", originalId);
	}

	public java.lang.Long getOriginalId() {
		return get("originalId");
	}

	public void setIsOnlyAm(java.lang.Integer isOnlyAm) {
		set("isOnlyAm", isOnlyAm);
	}

	public java.lang.Integer getIsOnlyAm() {
		return get("isOnlyAm");
	}

	public void setChannelUrl(java.lang.String channelUrl) {
		set("channel_url", channelUrl);
	}

	public java.lang.String getChannelUrl() {
		return get("channel_url");
	}

	public void setChannelArgs(java.lang.String channelArgs) {
		set("channel_Args", channelArgs);
	}

	public java.lang.String getChannelArgs() {
		return get("channel_Args");
	}

}
