package com.biz.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBizMember<M extends BaseBizMember<M>> extends Model<M> implements IBean {

	public void setPkMember(java.lang.Integer pkMember) {
		set("PK_MEMBER", pkMember);
	}

	public java.lang.Integer getPkMember() {
		return get("PK_MEMBER");
	}

	public void setLoginName(java.lang.String loginName) {
		set("LOGIN_NAME", loginName);
	}

	public java.lang.String getLoginName() {
		return get("LOGIN_NAME");
	}

	public void setLoginPwd(java.lang.String loginPwd) {
		set("LOGIN_PWD", loginPwd);
	}

	public java.lang.String getLoginPwd() {
		return get("LOGIN_PWD");
	}

	public void setRealName(java.lang.String realName) {
		set("REAL_NAME", realName);
	}

	public java.lang.String getRealName() {
		return get("REAL_NAME");
	}

	public void setSEX(java.lang.Integer SEX) {
		set("SEX", SEX);
	}

	public java.lang.Integer getSEX() {
		return get("SEX");
	}

	public void setBirthDay(java.util.Date birthDay) {
		set("BIRTH_DAY", birthDay);
	}

	public java.util.Date getBirthDay() {
		return get("BIRTH_DAY");
	}

	public void setHeadPortrait(java.lang.String headPortrait) {
		set("HEAD_PORTRAIT", headPortrait);
	}

	public java.lang.String getHeadPortrait() {
		return get("HEAD_PORTRAIT");
	}

	public void setDictCerType(java.lang.Integer dictCerType) {
		set("DICT_CER_TYPE", dictCerType);
	}

	public java.lang.Integer getDictCerType() {
		return get("DICT_CER_TYPE");
	}

	public void setCerNumber(java.lang.String cerNumber) {
		set("CER_NUMBER", cerNumber);
	}

	public java.lang.String getCerNumber() {
		return get("CER_NUMBER");
	}

	public void setPhoneNumber(java.lang.String phoneNumber) {
		set("PHONE_NUMBER", phoneNumber);
	}

	public java.lang.String getPhoneNumber() {
		return get("PHONE_NUMBER");
	}

	public void setEMail(java.lang.String eMail) {
		set("E_MAIL", eMail);
	}

	public java.lang.String getEMail() {
		return get("E_MAIL");
	}

	public void setDictMemberStatus(java.lang.Integer dictMemberStatus) {
		set("DICT_MEMBER_STATUS", dictMemberStatus);
	}

	public java.lang.Integer getDictMemberStatus() {
		return get("DICT_MEMBER_STATUS");
	}

	public void setDictMemberLevel(java.lang.String dictMemberLevel) {
		set("DICT_MEMBER_LEVEL", dictMemberLevel);
	}

	public java.lang.String getDictMemberLevel() {
		return get("DICT_MEMBER_LEVEL");
	}

	public void setRefereeId(java.lang.Integer refereeId) {
		set("REFEREE_ID", refereeId);
	}

	public java.lang.Integer getRefereeId() {
		return get("REFEREE_ID");
	}

	public void setRefereeCode(java.lang.String refereeCode) {
		set("REFEREE_CODE", refereeCode);
	}

	public java.lang.String getRefereeCode() {
		return get("REFEREE_CODE");
	}

	public void setRegChannel(java.lang.Integer regChannel) {
		set("REG_CHANNEL", regChannel);
	}

	public java.lang.Integer getRegChannel() {
		return get("REG_CHANNEL");
	}

	public void setRegTime(java.util.Date regTime) {
		set("REG_TIME", regTime);
	}

	public java.util.Date getRegTime() {
		return get("REG_TIME");
	}

	public void setIsActive(java.lang.Integer isActive) {
		set("IS_ACTIVE", isActive);
	}

	public java.lang.Integer getIsActive() {
		return get("IS_ACTIVE");
	}

	public void setREMARK(java.lang.String REMARK) {
		set("REMARK", REMARK);
	}

	public java.lang.String getREMARK() {
		return get("REMARK");
	}

	public void setLastLoginTime(java.util.Date lastLoginTime) {
		set("LAST_LOGIN_TIME", lastLoginTime);
	}

	public java.util.Date getLastLoginTime() {
		return get("LAST_LOGIN_TIME");
	}

	public void setLoginIp(java.lang.String loginIp) {
		set("LOGIN_IP", loginIp);
	}

	public java.lang.String getLoginIp() {
		return get("LOGIN_IP");
	}

	public void setCreateById(java.lang.Integer createById) {
		set("CREATE_BY_ID", createById);
	}

	public java.lang.Integer getCreateById() {
		return get("CREATE_BY_ID");
	}

	public void setCreateByTime(java.util.Date createByTime) {
		set("CREATE_BY_TIME", createByTime);
	}

	public java.util.Date getCreateByTime() {
		return get("CREATE_BY_TIME");
	}

	public void setUpdateById(java.lang.Integer updateById) {
		set("UPDATE_BY_ID", updateById);
	}

	public java.lang.Integer getUpdateById() {
		return get("UPDATE_BY_ID");
	}

	public void setUpdateByTime(java.util.Date updateByTime) {
		set("UPDATE_BY_TIME", updateByTime);
	}

	public java.util.Date getUpdateByTime() {
		return get("UPDATE_BY_TIME");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("IS_VALID", isValid);
	}

	public java.lang.Integer getIsValid() {
		return get("IS_VALID");
	}

}
