package com.biz.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBizArticleComment<M extends BaseBizArticleComment<M>> extends Model<M> implements IBean {

	public void setPkArticleComment(java.lang.Integer pkArticleComment) {
		set("PK_ARTICLE_COMMENT", pkArticleComment);
	}

	public java.lang.Integer getPkArticleComment() {
		return get("PK_ARTICLE_COMMENT");
	}

	public void setFkArticle(java.lang.Integer fkArticle) {
		set("FK_ARTICLE", fkArticle);
	}

	public java.lang.Integer getFkArticle() {
		return get("FK_ARTICLE");
	}

	public void setFkMember(java.lang.Integer fkMember) {
		set("FK_MEMBER", fkMember);
	}

	public java.lang.Integer getFkMember() {
		return get("FK_MEMBER");
	}

	public void setREALNAME(java.lang.String REALNAME) {
		set("REALNAME", REALNAME);
	}

	public java.lang.String getREALNAME() {
		return get("REALNAME");
	}

	public void setCONTENT(java.lang.String CONTENT) {
		set("CONTENT", CONTENT);
	}

	public java.lang.String getCONTENT() {
		return get("CONTENT");
	}

	public void setEMAIL(java.lang.String EMAIL) {
		set("EMAIL", EMAIL);
	}

	public java.lang.String getEMAIL() {
		return get("EMAIL");
	}

	public void setCONTACT(java.lang.String CONTACT) {
		set("CONTACT", CONTACT);
	}

	public java.lang.String getCONTACT() {
		return get("CONTACT");
	}

	public void setVisitIp(java.lang.String visitIp) {
		set("VISIT_IP", visitIp);
	}

	public java.lang.String getVisitIp() {
		return get("VISIT_IP");
	}

	public void setSTATUS(java.lang.Integer STATUS) {
		set("STATUS", STATUS);
	}

	public java.lang.Integer getSTATUS() {
		return get("STATUS");
	}

	public void setVisitDate(java.util.Date visitDate) {
		set("VISIT_DATE", visitDate);
	}

	public java.util.Date getVisitDate() {
		return get("VISIT_DATE");
	}

	public void setReplyContent(java.lang.String replyContent) {
		set("REPLY_CONTENT", replyContent);
	}

	public java.lang.String getReplyContent() {
		return get("REPLY_CONTENT");
	}

	public void setReplyDate(java.util.Date replyDate) {
		set("REPLY_DATE", replyDate);
	}

	public java.util.Date getReplyDate() {
		return get("REPLY_DATE");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("IS_VALID", isValid);
	}

	public java.lang.Integer getIsValid() {
		return get("IS_VALID");
	}

}
