package com.biz.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysDict<M extends BaseSysDict<M>> extends Model<M> implements IBean {

	public void setPkDict(java.lang.Integer pkDict) {
		set("PK_DICT", pkDict);
	}

	public java.lang.Integer getPkDict() {
		return get("PK_DICT");
	}

	public void setDictType(java.lang.String dictType) {
		set("DICT_TYPE", dictType);
	}

	public java.lang.String getDictType() {
		return get("DICT_TYPE");
	}

	public void setDictKey(java.lang.String dictKey) {
		set("DICT_KEY", dictKey);
	}

	public java.lang.String getDictKey() {
		return get("DICT_KEY");
	}

	public void setDictValue(java.lang.String dictValue) {
		set("DICT_VALUE", dictValue);
	}

	public java.lang.String getDictValue() {
		return get("DICT_VALUE");
	}

	public void setSortId(java.lang.Integer sortId) {
		set("SORT_ID", sortId);
	}

	public java.lang.Integer getSortId() {
		return get("SORT_ID");
	}

	public void setREMARK(java.lang.String REMARK) {
		set("REMARK", REMARK);
	}

	public java.lang.String getREMARK() {
		return get("REMARK");
	}

	public void setCreateById(java.lang.Integer createById) {
		set("CREATE_BY_ID", createById);
	}

	public java.lang.Integer getCreateById() {
		return get("CREATE_BY_ID");
	}

	public void setCreateByTime(java.util.Date createByTime) {
		set("CREATE_BY_TIME", createByTime);
	}

	public java.util.Date getCreateByTime() {
		return get("CREATE_BY_TIME");
	}

	public void setUpdateById(java.lang.Integer updateById) {
		set("UPDATE_BY_ID", updateById);
	}

	public java.lang.Integer getUpdateById() {
		return get("UPDATE_BY_ID");
	}

	public void setUpdateByTime(java.util.Date updateByTime) {
		set("UPDATE_BY_TIME", updateByTime);
	}

	public java.util.Date getUpdateByTime() {
		return get("UPDATE_BY_TIME");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("IS_VALID", isValid);
	}

	public java.lang.Integer getIsValid() {
		return get("IS_VALID");
	}

}
