package com.biz.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBizArticleTagRef<M extends BaseBizArticleTagRef<M>> extends Model<M> implements IBean {

	public void setPkArticleTagRef(java.lang.Integer pkArticleTagRef) {
		set("PK_ARTICLE_TAG_REF", pkArticleTagRef);
	}

	public java.lang.Integer getPkArticleTagRef() {
		return get("PK_ARTICLE_TAG_REF");
	}

	public void setFkArticle(java.lang.Integer fkArticle) {
		set("FK_ARTICLE", fkArticle);
	}

	public java.lang.Integer getFkArticle() {
		return get("FK_ARTICLE");
	}

	public void setFkArticleTag(java.lang.Integer fkArticleTag) {
		set("FK_ARTICLE_TAG", fkArticleTag);
	}

	public java.lang.Integer getFkArticleTag() {
		return get("FK_ARTICLE_TAG");
	}

	public void setMemberCreateById(java.lang.Integer memberCreateById) {
		set("MEMBER_CREATE_BY_ID", memberCreateById);
	}

	public java.lang.Integer getMemberCreateById() {
		return get("MEMBER_CREATE_BY_ID");
	}

	public void setMemberCreateByTime(java.util.Date memberCreateByTime) {
		set("MEMBER_CREATE_BY_TIME", memberCreateByTime);
	}

	public java.util.Date getMemberCreateByTime() {
		return get("MEMBER_CREATE_BY_TIME");
	}

	public void setMemberUpdateById(java.lang.Integer memberUpdateById) {
		set("MEMBER_UPDATE_BY_ID", memberUpdateById);
	}

	public java.lang.Integer getMemberUpdateById() {
		return get("MEMBER_UPDATE_BY_ID");
	}

	public void setMemberUpdateByTime(java.util.Date memberUpdateByTime) {
		set("MEMBER_UPDATE_BY_TIME", memberUpdateByTime);
	}

	public java.util.Date getMemberUpdateByTime() {
		return get("MEMBER_UPDATE_BY_TIME");
	}

	public void setCreateById(java.lang.Integer createById) {
		set("CREATE_BY_ID", createById);
	}

	public java.lang.Integer getCreateById() {
		return get("CREATE_BY_ID");
	}

	public void setCreateByTime(java.util.Date createByTime) {
		set("CREATE_BY_TIME", createByTime);
	}

	public java.util.Date getCreateByTime() {
		return get("CREATE_BY_TIME");
	}

	public void setUpdateById(java.lang.Integer updateById) {
		set("UPDATE_BY_ID", updateById);
	}

	public java.lang.Integer getUpdateById() {
		return get("UPDATE_BY_ID");
	}

	public void setUpdateByTime(java.util.Date updateByTime) {
		set("UPDATE_BY_TIME", updateByTime);
	}

	public java.util.Date getUpdateByTime() {
		return get("UPDATE_BY_TIME");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("IS_VALID", isValid);
	}

	public java.lang.Integer getIsValid() {
		return get("IS_VALID");
	}

}
