package com.biz.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBizArticle<M extends BaseBizArticle<M>> extends Model<M> implements IBean {

	public void setPkArticle(java.lang.Integer pkArticle) {
		set("PK_ARTICLE", pkArticle);
	}

	public java.lang.Integer getPkArticle() {
		return get("PK_ARTICLE");
	}

	public void setFkMember(java.lang.Integer fkMember) {
		set("FK_MEMBER", fkMember);
	}

	public java.lang.Integer getFkMember() {
		return get("FK_MEMBER");
	}

	public void setFkArticleCategory(java.lang.Integer fkArticleCategory) {
		set("FK_ARTICLE_CATEGORY", fkArticleCategory);
	}

	public java.lang.Integer getFkArticleCategory() {
		return get("FK_ARTICLE_CATEGORY");
	}

	public void setTITLE(java.lang.String TITLE) {
		set("TITLE", TITLE);
	}

	public java.lang.String getTITLE() {
		return get("TITLE");
	}

	public void setTopPicture(java.lang.String topPicture) {
		set("TOP_PICTURE", topPicture);
	}

	public java.lang.String getTopPicture() {
		return get("TOP_PICTURE");
	}

	public void setTopPictureMin(java.lang.String topPictureMin) {
		set("TOP_PICTURE_MIN", topPictureMin);
	}

	public java.lang.String getTopPictureMin() {
		return get("TOP_PICTURE_MIN");
	}

	public void setCoverPicture(java.lang.String coverPicture) {
		set("COVER_PICTURE", coverPicture);
	}

	public java.lang.String getCoverPicture() {
		return get("COVER_PICTURE");
	}

	public void setCoverPictureMin(java.lang.String coverPictureMin) {
		set("COVER_PICTURE_MIN", coverPictureMin);
	}

	public java.lang.String getCoverPictureMin() {
		return get("COVER_PICTURE_MIN");
	}

	public void setEditType(java.lang.Integer editType) {
		set("EDIT_TYPE", editType);
	}

	public java.lang.Integer getEditType() {
		return get("EDIT_TYPE");
	}

	public void setCONTENT(java.lang.String CONTENT) {
		set("CONTENT", CONTENT);
	}

	public java.lang.String getCONTENT() {
		return get("CONTENT");
	}
	
	public void setPreContent(java.lang.String preContent) {
		set("PRE_CONTENT", preContent);
	}

	public java.lang.String getPreContent() {
		return get("PRE_CONTENT");
	}

	public void setPublishedDate(java.util.Date publishedDate) {
		set("PUBLISHED_DATE", publishedDate);
	}

	public java.util.Date getPublishedDate() {
		return get("PUBLISHED_DATE");
	}

	public void setIsOriginal(java.lang.Integer isOriginal) {
		set("IS_ORIGINAL", isOriginal);
	}

	public java.lang.Integer getIsOriginal() {
		return get("IS_ORIGINAL");
	}

	public void setReprintAddress(java.lang.String reprintAddress) {
		set("REPRINT_ADDRESS", reprintAddress);
	}

	public java.lang.String getReprintAddress() {
		return get("REPRINT_ADDRESS");
	}

	public void setMEMO(java.lang.String MEMO) {
		set("MEMO", MEMO);
	}

	public java.lang.String getMEMO() {
		return get("MEMO");
	}

	public void setMemberCreateById(java.lang.Integer memberCreateById) {
		set("MEMBER_CREATE_BY_ID", memberCreateById);
	}

	public java.lang.Integer getMemberCreateById() {
		return get("MEMBER_CREATE_BY_ID");
	}

	public void setMemberCreateByTime(java.util.Date memberCreateByTime) {
		set("MEMBER_CREATE_BY_TIME", memberCreateByTime);
	}

	public java.util.Date getMemberCreateByTime() {
		return get("MEMBER_CREATE_BY_TIME");
	}

	public void setMemberUpdateById(java.lang.Integer memberUpdateById) {
		set("MEMBER_UPDATE_BY_ID", memberUpdateById);
	}

	public java.lang.Integer getMemberUpdateById() {
		return get("MEMBER_UPDATE_BY_ID");
	}

	public void setMemberUpdateByTime(java.util.Date memberUpdateByTime) {
		set("MEMBER_UPDATE_BY_TIME", memberUpdateByTime);
	}

	public java.util.Date getMemberUpdateByTime() {
		return get("MEMBER_UPDATE_BY_TIME");
	}

	public void setCreateById(java.lang.Integer createById) {
		set("CREATE_BY_ID", createById);
	}

	public java.lang.Integer getCreateById() {
		return get("CREATE_BY_ID");
	}

	public void setCreateByTime(java.util.Date createByTime) {
		set("CREATE_BY_TIME", createByTime);
	}

	public java.util.Date getCreateByTime() {
		return get("CREATE_BY_TIME");
	}

	public void setUpdateById(java.lang.Integer updateById) {
		set("UPDATE_BY_ID", updateById);
	}

	public java.lang.Integer getUpdateById() {
		return get("UPDATE_BY_ID");
	}

	public void setUpdateByTime(java.util.Date updateByTime) {
		set("UPDATE_BY_TIME", updateByTime);
	}

	public java.util.Date getUpdateByTime() {
		return get("UPDATE_BY_TIME");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("IS_VALID", isValid);
	}

	public java.lang.Integer getIsValid() {
		return get("IS_VALID");
	}

}
