package com.biz.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysSmsProduct<M extends BaseSysSmsProduct<M>> extends Model<M> implements IBean {

	public void setPkSysSmsProduct(java.lang.Integer pkSysSmsProduct) {
		set("pk_sys_sms_product", pkSysSmsProduct);
	}

	public java.lang.Integer getPkSysSmsProduct() {
		return get("pk_sys_sms_product");
	}

	public void setProductName(java.lang.String productName) {
		set("product_name", productName);
	}

	public java.lang.String getProductName() {
		return get("product_name");
	}

	public void setFkSysSmsChannel(java.lang.Integer fkSysSmsChannel) {
		set("fk_sys_sms_channel", fkSysSmsChannel);
	}

	public java.lang.Integer getFkSysSmsChannel() {
		return get("fk_sys_sms_channel");
	}

	public void setSmsType(java.lang.String smsType) {
		set("sms_type", smsType);
	}

	public java.lang.String getSmsType() {
		return get("sms_type");
	}

}
