package com.biz.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysSmsChannel<M extends BaseSysSmsChannel<M>> extends Model<M> implements IBean {

	public void setPkSysSmsChannel(java.lang.Integer pkSysSmsChannel) {
		set("pk_sys_sms_channel", pkSysSmsChannel);
	}

	public java.lang.Integer getPkSysSmsChannel() {
		return get("pk_sys_sms_channel");
	}

	public void setChannelName(java.lang.String channelName) {
		set("channel_name", channelName);
	}

	public java.lang.String getChannelName() {
		return get("channel_name");
	}

	public void setChannelUrl(java.lang.String channelUrl) {
		set("channel_url", channelUrl);
	}

	public java.lang.String getChannelUrl() {
		return get("channel_url");
	}

	public void setChannelSign(java.lang.String channelSign) {
		set("channel_sign", channelSign);
	}

	public java.lang.String getChannelSign() {
		return get("channel_sign");
	}

	public void setChannelStatus(java.lang.Integer channelStatus) {
		set("channel_status", channelStatus);
	}

	public java.lang.Integer getChannelStatus() {
		return get("channel_status");
	}

	public void setChannelOrder(java.lang.Integer channelOrder) {
		set("channel_order", channelOrder);
	}

	public java.lang.Integer getChannelOrder() {
		return get("channel_order");
	}

	public void setChannelCode(java.lang.String channelCode) {
		set("channel_code", channelCode);
	}

	public java.lang.String getChannelCode() {
		return get("channel_code");
	}

}
