package com.biz.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysUser<M extends BaseSysUser<M>> extends Model<M> implements IBean {

	public void setPkUser(java.lang.Integer pkUser) {
		set("PK_USER", pkUser);
	}

	public java.lang.Integer getPkUser() {
		return get("PK_USER");
	}

	public void setUserName(java.lang.String userName) {
		set("USER_NAME", userName);
	}

	public java.lang.String getUserName() {
		return get("USER_NAME");
	}

	public void setPASSWORD(java.lang.String PASSWORD) {
		set("PASSWORD", PASSWORD);
	}

	public java.lang.String getPASSWORD() {
		return get("PASSWORD");
	}

	public void setRealName(java.lang.String realName) {
		set("REAL_NAME", realName);
	}

	public java.lang.String getRealName() {
		return get("REAL_NAME");
	}

	public void setUserLevel(java.lang.Integer userLevel) {
		set("USER_LEVEL", userLevel);
	}

	public java.lang.Integer getUserLevel() {
		return get("USER_LEVEL");
	}

	public void setUserType(java.lang.Integer userType) {
		set("USER_TYPE", userType);
	}

	public java.lang.Integer getUserType() {
		return get("USER_TYPE");
	}

	public void setPHONE(java.lang.String PHONE) {
		set("PHONE", PHONE);
	}

	public java.lang.String getPHONE() {
		return get("PHONE");
	}

	public void setEmailAddr(java.lang.String emailAddr) {
		set("EMAIL_ADDR", emailAddr);
	}

	public java.lang.String getEmailAddr() {
		return get("EMAIL_ADDR");
	}

	public void setSTATUS(java.lang.Integer STATUS) {
		set("STATUS", STATUS);
	}

	public java.lang.Integer getSTATUS() {
		return get("STATUS");
	}

	public void setJoinTime(java.util.Date joinTime) {
		set("JOIN_TIME", joinTime);
	}

	public java.util.Date getJoinTime() {
		return get("JOIN_TIME");
	}

	public void setLastLoginTime(java.util.Date lastLoginTime) {
		set("LAST_LOGIN_TIME", lastLoginTime);
	}

	public java.util.Date getLastLoginTime() {
		return get("LAST_LOGIN_TIME");
	}

	public void setLanSetting(java.lang.String lanSetting) {
		set("LAN_SETTING", lanSetting);
	}

	public java.lang.String getLanSetting() {
		return get("LAN_SETTING");
	}

	public void setCreateById(java.lang.Integer createById) {
		set("CREATE_BY_ID", createById);
	}

	public java.lang.Integer getCreateById() {
		return get("CREATE_BY_ID");
	}

	public void setCreateByTime(java.util.Date createByTime) {
		set("CREATE_BY_TIME", createByTime);
	}

	public java.util.Date getCreateByTime() {
		return get("CREATE_BY_TIME");
	}

	public void setUpdateById(java.lang.Integer updateById) {
		set("UPDATE_BY_ID", updateById);
	}

	public java.lang.Integer getUpdateById() {
		return get("UPDATE_BY_ID");
	}

	public void setUpdateByTime(java.util.Date updateByTime) {
		set("UPDATE_BY_TIME", updateByTime);
	}

	public java.util.Date getUpdateByTime() {
		return get("UPDATE_BY_TIME");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("IS_VALID", isValid);
	}

	public java.lang.Integer getIsValid() {
		return get("IS_VALID");
	}

}
