package com.biz.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBizNavigatorCategory<M extends BaseBizNavigatorCategory<M>> extends Model<M> implements IBean {

	public void setPkNavigatorCategory(java.lang.Integer pkNavigatorCategory) {
		set("PK_NAVIGATOR_CATEGORY", pkNavigatorCategory);
	}

	public java.lang.Integer getPkNavigatorCategory() {
		return get("PK_NAVIGATOR_CATEGORY");
	}

	public void setFkMember(java.lang.Integer fkMember) {
		set("FK_MEMBER", fkMember);
	}

	public java.lang.Integer getFkMember() {
		return get("FK_MEMBER");
	}

	public void setCategoryName(java.lang.String categoryName) {
		set("CATEGORY_NAME", categoryName);
	}

	public java.lang.String getCategoryName() {
		return get("CATEGORY_NAME");
	}

	public void setIsSystem(java.lang.Integer isSystem) {
		set("IS_SYSTEM", isSystem);
	}

	public java.lang.Integer getIsSystem() {
		return get("IS_SYSTEM");
	}

	public void setMEMO(java.lang.String MEMO) {
		set("MEMO", MEMO);
	}

	public java.lang.String getMEMO() {
		return get("MEMO");
	}

	public void setCreateById(java.lang.Integer createById) {
		set("CREATE_BY_ID", createById);
	}

	public java.lang.Integer getCreateById() {
		return get("CREATE_BY_ID");
	}

	public void setCreateByTime(java.util.Date createByTime) {
		set("CREATE_BY_TIME", createByTime);
	}

	public java.util.Date getCreateByTime() {
		return get("CREATE_BY_TIME");
	}

	public void setUpdateById(java.lang.Integer updateById) {
		set("UPDATE_BY_ID", updateById);
	}

	public java.lang.Integer getUpdateById() {
		return get("UPDATE_BY_ID");
	}

	public void setUpdateByTime(java.util.Date updateByTime) {
		set("UPDATE_BY_TIME", updateByTime);
	}

	public java.util.Date getUpdateByTime() {
		return get("UPDATE_BY_TIME");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("IS_VALID", isValid);
	}

	public java.lang.Integer getIsValid() {
		return get("IS_VALID");
	}

}
