package com.biz.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysMenu<M extends BaseSysMenu<M>> extends Model<M> implements IBean {

	public void setPkMenu(java.lang.Integer pkMenu) {
		set("PK_MENU", pkMenu);
	}

	public java.lang.Integer getPkMenu() {
		return get("PK_MENU");
	}

	public void setMenuName(java.lang.String menuName) {
		set("MENU_NAME", menuName);
	}

	public java.lang.String getMenuName() {
		return get("MENU_NAME");
	}

	public void setMenuLevel(java.lang.Integer menuLevel) {
		set("MENU_LEVEL", menuLevel);
	}

	public java.lang.Integer getMenuLevel() {
		return get("MENU_LEVEL");
	}

	public void setMenuHref(java.lang.String menuHref) {
		set("MENU_HREF", menuHref);
	}

	public java.lang.String getMenuHref() {
		return get("MENU_HREF");
	}

	public void setOrderNo(java.lang.Integer orderNo) {
		set("ORDER_NO", orderNo);
	}

	public java.lang.Integer getOrderNo() {
		return get("ORDER_NO");
	}

	public void setMenuStatus(java.lang.Integer menuStatus) {
		set("MENU_STATUS", menuStatus);
	}

	public java.lang.Integer getMenuStatus() {
		return get("MENU_STATUS");
	}

	public void setPID(java.lang.String PID) {
		set("PID", PID);
	}

	public java.lang.String getPID() {
		return get("PID");
	}

	public void setCreateById(java.lang.Integer createById) {
		set("CREATE_BY_ID", createById);
	}

	public java.lang.Integer getCreateById() {
		return get("CREATE_BY_ID");
	}

	public void setCreateByTime(java.util.Date createByTime) {
		set("CREATE_BY_TIME", createByTime);
	}

	public java.util.Date getCreateByTime() {
		return get("CREATE_BY_TIME");
	}

	public void setUpdateById(java.lang.Integer updateById) {
		set("UPDATE_BY_ID", updateById);
	}

	public java.lang.Integer getUpdateById() {
		return get("UPDATE_BY_ID");
	}

	public void setUpdateByTime(java.util.Date updateByTime) {
		set("UPDATE_BY_TIME", updateByTime);
	}

	public java.util.Date getUpdateByTime() {
		return get("UPDATE_BY_TIME");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("IS_VALID", isValid);
	}

	public java.lang.Integer getIsValid() {
		return get("IS_VALID");
	}

}
