package com.biz.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("biz_article", "PK_ARTICLE", BizArticle.class);
		arp.addMapping("biz_article_category", "PK_ARTICLE_CATEGORY", BizArticleCategory.class);
		arp.addMapping("biz_article_collection", "PK_ARTICLE_COLLECTION", BizArticleCollection.class);
		arp.addMapping("biz_article_comment", "PK_ARTICLE_COMMENT", BizArticleComment.class);
		arp.addMapping("biz_article_like", "PK_ARTICLE_LIKE", BizArticleLike.class);
		arp.addMapping("biz_article_tag", "PK_ARTICLE_TAG", BizArticleTag.class);
		arp.addMapping("biz_article_tag_ref", "PK_ARTICLE_TAG_REF", BizArticleTagRef.class);
		arp.addMapping("biz_member", "PK_MEMBER", BizMember.class);
		arp.addMapping("biz_member_navigator", "PK_MEMBER_NAVIGATOR", BizMemberNavigator.class);
		arp.addMapping("biz_navigator", "PK_NAVIGATOR", BizNavigator.class);
		arp.addMapping("biz_navigator_category", "PK_NAVIGATOR_CATEGORY", BizNavigatorCategory.class);
		arp.addMapping("sys_area", "PK_AREA", SysArea.class);
		arp.addMapping("sys_dict", "PK_DICT", SysDict.class);
		arp.addMapping("sys_language_cfg", "PK_LANGUAGE_CFG", SysLanguageCfg.class);
		arp.addMapping("sys_log", "PK_LOG", SysLog.class);
		arp.addMapping("sys_menu", "PK_MENU", SysMenu.class);
		arp.addMapping("sys_role", "PK_ROLE", SysRole.class);
		arp.addMapping("sys_role_menu", "PK_ROLE_MENU", SysRoleMenu.class);
		arp.addMapping("sys_sms", "id", SysSms.class);
		arp.addMapping("sys_sms_args", "pk_sys_sms_args", SysSmsArgs.class);
		arp.addMapping("sys_sms_channel", "pk_sys_sms_channel", SysSmsChannel.class);
		arp.addMapping("sys_sms_product", "pk_sys_sms_product", SysSmsProduct.class);
		arp.addMapping("sys_user", "PK_USER", SysUser.class);
		arp.addMapping("sys_user_role", "PK_USER_ROLE", SysUserRole.class);
	}
}

