package com.biz.model;

import com.biz.model.base.BaseBizArticleComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BizArticleComment extends BaseBizArticleComment<BizArticleComment> {
	public static final BizArticleComment dao = new BizArticleComment();
}
