package com.biz.model;

import com.biz.model.base.BaseBizArticleCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BizArticleCategory extends BaseBizArticleCategory<BizArticleCategory> {
	public static final BizArticleCategory dao = new BizArticleCategory();
}
