package com.biz.model;

import com.biz.model.base.BaseBizArticleTag;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BizArticleTag extends BaseBizArticleTag<BizArticleTag> {
	public static final BizArticleTag dao = new BizArticleTag();
}
