package com.biz.model;

import com.biz.model.base.BaseBizArticleCollection;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BizArticleCollection extends BaseBizArticleCollection<BizArticleCollection> {
	public static final BizArticleCollection dao = new BizArticleCollection();
}
