package com.biz.model;

import com.biz.model.base.BaseBizArticle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BizArticle extends BaseBizArticle<BizArticle> {
	public static final BizArticle dao = new BizArticle();
}
