package com.biz.model;

import com.biz.model.base.BaseBizArticleTagRef;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BizArticleTagRef extends BaseBizArticleTagRef<BizArticleTagRef> {
	public static final BizArticleTagRef dao = new BizArticleTagRef();
}
