package com.biz.model;

import com.biz.model.base.BaseBizArticleLike;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BizArticleLike extends BaseBizArticleLike<BizArticleLike> {
	public static final BizArticleLike dao = new BizArticleLike();
}
