package com.biz.model;

import com.biz.model.base.BaseBizMemberNavigator;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BizMemberNavigator extends BaseBizMemberNavigator<BizMemberNavigator> {
	public static final BizMemberNavigator dao = new BizMemberNavigator();
}
