package com.biz.model;

import com.biz.model.base.BaseBizMember;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BizMember extends BaseBizMember<BizMember> {
	public static final BizMember dao = new BizMember();
}
