package com.biz.model;

import com.biz.model.base.BaseBizNavigatorCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BizNavigatorCategory extends BaseBizNavigatorCategory<BizNavigatorCategory> {
	public static final BizNavigatorCategory dao = new BizNavigatorCategory();
}
