package com.biz.model;

import com.biz.model.base.BaseBizNavigator;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BizNavigator extends BaseBizNavigator<BizNavigator> {
	public static final BizNavigator dao = new BizNavigator();
}
