package com.biz.model;

import com.biz.model.base.BaseSysArea;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysArea extends BaseSysArea<SysArea> {
	public static final SysArea dao = new SysArea();
}
