package com.biz.model;

import com.biz.model.base.BaseSysLanguageCfg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysLanguageCfg extends BaseSysLanguageCfg<SysLanguageCfg> {
	public static final SysLanguageCfg dao = new SysLanguageCfg();
}
