package com.biz.model;

import com.biz.model.base.BaseSysSmsChannel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysSmsChannel extends BaseSysSmsChannel<SysSmsChannel> {
	public static final SysSmsChannel dao = new SysSmsChannel();
}
