package com.biz.model;

import com.biz.model.base.BaseSysSmsArgs;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysSmsArgs extends BaseSysSmsArgs<SysSmsArgs> {
	public static final SysSmsArgs dao = new SysSmsArgs();
}
