package com.biz.model;

import com.biz.model.base.BaseSysSmsProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysSmsProduct extends BaseSysSmsProduct<SysSmsProduct> {
	public static final SysSmsProduct dao = new SysSmsProduct();
}
