package com.biz.model;

import com.biz.model.base.BaseSysSms;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysSms extends BaseSysSms<SysSms> {
	public static final SysSms dao = new SysSms();
}
