package com.biz.model;

import com.biz.model.base.BaseSysUserRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUserRole extends BaseSysUserRole<SysUserRole> {
	public static final SysUserRole dao = new SysUserRole();
}
